services:
  db:
    image: mysql:8.0
    ports:
      - "${PORT_DATABASE}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

    
  api:
    build:
      context: ./backend
    ports:
      - "${APP_ENV}:8000"
    volumes:
      - ./backend/app:/app
    depends_on:
      - db
    networks:
      - backend_net


networks:
  backend_net:
  frontend_net:

volumes:
  mysql_data: