services:
  db:
    image: mysql:8.0
    ports:
      - "${PORT_DATABASE}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - backend_net
    
  api:
    build:
      context: ./backend
    ports:
      - "${APP_ENV}:8000"
    volumes:
      - ./backend/app:/app
    networks:
      - frontend_net
      - backend_net


networks:
  backend_net:
  frontend_net:

volumes:
  mysql_data: